### ISSUE TITLE
Parse the taamim

### ISSUE THREAD

**Issue by jordanguardio** [avi-perl/Hebrew#10]
Hey,

Is there a way to parse the taamin. For example

Hebrew(אָדָ֛ם).taam = 'Tevir' 

Thanks,

Jordan

**Comment by avi-perl** [comment]
Would you mind expanding on what you are looking to do, perhaps develop the
code sample so that I can get a better understanding?

Thanks!

**Comment by avi-perl** [comment]
Hi, 

I was initially confused by the issue but believe I have an understanding of what you are trying to accomplish. While a specific method for extracting the names of taamin that exist in a string does not exist, it is possible to do with some of the tools provided in the library. Here is a code snippet that extracts a list of unique taamin that are found in a string by name:

```python
from collections import Counter

from hebrew import Hebrew, TAAMIM_CHARS
from hebrew.chars import CHARS

if __name__ == "__main__":
    # Extract each instance of a taamim and get the TaamimChar instance for each
    taamim = [
        CHARS.get(c) for c in
        Hebrew("בְּרֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ׃").string
        if CHARS.get(c) and CHARS.get(c) in TAAMIM_CHARS
    ]

    # Get the name of all the found taamim
    taamim_names = [t.name for t in taamim]

    # print a count of how many times each taam appeared
    print(Counter(taamim_names))  # Counter({'Tifcha': 2, 'Mercha': 2, 'Munach': 1, 'Etnahta': 1, 'Meteg': 1})
```
